##                                ##
##           System Setup         ##
##                                ##
CACHE:                  True
CODON_SIZE:             100
DEBUG:                  True 
DEBUG_NET:              False 
VERBOSE:                True
CUDA_ENABLED:           False
DATASET:                5
##                                ##
##             GP Setup           ##
##                                ##
GRAMMAR_FILE:           evo_image_proc.bnf
FITNESS_FUNCTION:       cifar10 
INITIALISATION:         PI_grow
INVALID_SELECTION:      False
REPLACEMENT:            generational
SELECTION:              tournament
MUTATION:               int_flip_per_codon
CROSSOVER:              variable_onepoint
CROSSOVER_PROBABILITY:  0.75
TOURNAMENT_SIZE:        10
MAX_GENOME_LENGTH:      500
GENERATIONS:            50
POPULATION_SIZE:        30
MIN_INIT_TREE_DEPTH:    8
MAX_INIT_TREE_DEPTH:    10
MAX_TREE_DEPTH:         10
PARENT_FILE:            local_params.txt
##                                ##
##          Network Setup         ##
##                                ##
CONVOLUTION:            True
NETWORK_MODEL:          ConvModel 
CROSS_VALIDATION_SPLIT: 3
TRAIN_FREQ:             10
VALIDATION_FREQ:        50
NUM_EPOCHS:             3000 
BATCH_SIZE:             300
LEARNING_RATE:          0.1
MOMENTUM:               0.2
FCN_LAYERS:             [256, 10]
CONV_LAYERS:            [(64, 11, None, 4, True), (192, 5, None, 1, True), (384, 3, None, 1, False), (256, 3, None, 1, False), (256, 3, None, 1, True)]
AUGMENT_CHANNEL:        True
##                                ##
##     Preprocess / Early Stop    ##
##                                ##
EVOLVE_NETWORK:         True
RANDOM_SEED:            None
RESIZE:                 None 
NORMALIZE:              True
INPUT_CHANNEL:          3
KERNEL_GROW_RATE:       2
EARLY_STOP_FREQ:        3
EARLY_STOP_EPSILON:     1e-3
